apiVersion: apps/v1
kind: Deployment 
metadata:
  name: fastapi-app
  namespace: dev 
  labels:
    app: fastapi-app
    env: dev
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
        env: dev
    spec:
      containers:
        - name: fastapi-app
          image: amandabral9954/fastapi-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: dev 
            - name: VERSION
              value: "2.0.0"
            - name: FAIL_HEALTH
              value: "true"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 3
          
