apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: prod
  labels:
    app: fastapi-app
    environment: prod
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
        environment: prod
    spec:
      containers:
      - name: fastapi-app
        image: amandabral9954/fastapi-app:18
        ports:
        - containerPort: 8000
        env:
          - name: ENVIRONMENT
            value: production
          - name: VERSION
            value: "2.0.0"
          - name: FAIL_HEALTH
            value: "false"
        imagePullPolicy: IfNotPresent 
        resources:
          requests:
            memory: "512Mi"
            cpu: "400m"
          limits:
            memory: "1Gi"
            cpu: "800m"
        livenessProbe:
          httpGet:
            path: /health 
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 3
